// Code generated by go-swagger; DO NOT EDIT.

package components

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteComponentsIDParams creates a new DeleteComponentsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteComponentsIDParams() *DeleteComponentsIDParams {
	return &DeleteComponentsIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteComponentsIDParamsWithTimeout creates a new DeleteComponentsIDParams object
// with the ability to set a timeout on a request.
func NewDeleteComponentsIDParamsWithTimeout(timeout time.Duration) *DeleteComponentsIDParams {
	return &DeleteComponentsIDParams{
		timeout: timeout,
	}
}

// NewDeleteComponentsIDParamsWithContext creates a new DeleteComponentsIDParams object
// with the ability to set a context for a request.
func NewDeleteComponentsIDParamsWithContext(ctx context.Context) *DeleteComponentsIDParams {
	return &DeleteComponentsIDParams{
		Context: ctx,
	}
}

// NewDeleteComponentsIDParamsWithHTTPClient creates a new DeleteComponentsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteComponentsIDParamsWithHTTPClient(client *http.Client) *DeleteComponentsIDParams {
	return &DeleteComponentsIDParams{
		HTTPClient: client,
	}
}

/*
DeleteComponentsIDParams contains all the parameters to send to the API endpoint

	for the delete components ID operation.

	Typically these are written to a http.Request.
*/
type DeleteComponentsIDParams struct {

	/* ID.

	   ID компонента
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete components ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteComponentsIDParams) WithDefaults() *DeleteComponentsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete components ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteComponentsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete components ID params
func (o *DeleteComponentsIDParams) WithTimeout(timeout time.Duration) *DeleteComponentsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete components ID params
func (o *DeleteComponentsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete components ID params
func (o *DeleteComponentsIDParams) WithContext(ctx context.Context) *DeleteComponentsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete components ID params
func (o *DeleteComponentsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete components ID params
func (o *DeleteComponentsIDParams) WithHTTPClient(client *http.Client) *DeleteComponentsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete components ID params
func (o *DeleteComponentsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete components ID params
func (o *DeleteComponentsIDParams) WithID(id string) *DeleteComponentsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete components ID params
func (o *DeleteComponentsIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteComponentsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
