// Code generated by go-swagger; DO NOT EDIT.

package components

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetComponentsIDParams creates a new GetComponentsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetComponentsIDParams() *GetComponentsIDParams {
	return &GetComponentsIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetComponentsIDParamsWithTimeout creates a new GetComponentsIDParams object
// with the ability to set a timeout on a request.
func NewGetComponentsIDParamsWithTimeout(timeout time.Duration) *GetComponentsIDParams {
	return &GetComponentsIDParams{
		timeout: timeout,
	}
}

// NewGetComponentsIDParamsWithContext creates a new GetComponentsIDParams object
// with the ability to set a context for a request.
func NewGetComponentsIDParamsWithContext(ctx context.Context) *GetComponentsIDParams {
	return &GetComponentsIDParams{
		Context: ctx,
	}
}

// NewGetComponentsIDParamsWithHTTPClient creates a new GetComponentsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetComponentsIDParamsWithHTTPClient(client *http.Client) *GetComponentsIDParams {
	return &GetComponentsIDParams{
		HTTPClient: client,
	}
}

/*
GetComponentsIDParams contains all the parameters to send to the API endpoint

	for the get components ID operation.

	Typically these are written to a http.Request.
*/
type GetComponentsIDParams struct {

	/* ID.

	   ID компонента
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get components ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetComponentsIDParams) WithDefaults() *GetComponentsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get components ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetComponentsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get components ID params
func (o *GetComponentsIDParams) WithTimeout(timeout time.Duration) *GetComponentsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get components ID params
func (o *GetComponentsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get components ID params
func (o *GetComponentsIDParams) WithContext(ctx context.Context) *GetComponentsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get components ID params
func (o *GetComponentsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get components ID params
func (o *GetComponentsIDParams) WithHTTPClient(client *http.Client) *GetComponentsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get components ID params
func (o *GetComponentsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get components ID params
func (o *GetComponentsIDParams) WithID(id string) *GetComponentsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get components ID params
func (o *GetComponentsIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetComponentsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
