// Code generated by go-swagger; DO NOT EDIT.

package components

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/sm8ta/webike_bike_microservice_nikita/models"
)

// NewPostComponentsParams creates a new PostComponentsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostComponentsParams() *PostComponentsParams {
	return &PostComponentsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostComponentsParamsWithTimeout creates a new PostComponentsParams object
// with the ability to set a timeout on a request.
func NewPostComponentsParamsWithTimeout(timeout time.Duration) *PostComponentsParams {
	return &PostComponentsParams{
		timeout: timeout,
	}
}

// NewPostComponentsParamsWithContext creates a new PostComponentsParams object
// with the ability to set a context for a request.
func NewPostComponentsParamsWithContext(ctx context.Context) *PostComponentsParams {
	return &PostComponentsParams{
		Context: ctx,
	}
}

// NewPostComponentsParamsWithHTTPClient creates a new PostComponentsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostComponentsParamsWithHTTPClient(client *http.Client) *PostComponentsParams {
	return &PostComponentsParams{
		HTTPClient: client,
	}
}

/*
PostComponentsParams contains all the parameters to send to the API endpoint

	for the post components operation.

	Typically these are written to a http.Request.
*/
type PostComponentsParams struct {

	/* Request.

	   Данные компонента
	*/
	Request *models.InternalAdapterHandlerHTTPComponentRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post components params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostComponentsParams) WithDefaults() *PostComponentsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post components params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostComponentsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post components params
func (o *PostComponentsParams) WithTimeout(timeout time.Duration) *PostComponentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post components params
func (o *PostComponentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post components params
func (o *PostComponentsParams) WithContext(ctx context.Context) *PostComponentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post components params
func (o *PostComponentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post components params
func (o *PostComponentsParams) WithHTTPClient(client *http.Client) *PostComponentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post components params
func (o *PostComponentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post components params
func (o *PostComponentsParams) WithRequest(request *models.InternalAdapterHandlerHTTPComponentRequest) *PostComponentsParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post components params
func (o *PostComponentsParams) SetRequest(request *models.InternalAdapterHandlerHTTPComponentRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostComponentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
