// Code generated by go-swagger; DO NOT EDIT.

package components

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/sm8ta/webike_bike_microservice_nikita/models"
)

// NewPutComponentsIDParams creates a new PutComponentsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutComponentsIDParams() *PutComponentsIDParams {
	return &PutComponentsIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutComponentsIDParamsWithTimeout creates a new PutComponentsIDParams object
// with the ability to set a timeout on a request.
func NewPutComponentsIDParamsWithTimeout(timeout time.Duration) *PutComponentsIDParams {
	return &PutComponentsIDParams{
		timeout: timeout,
	}
}

// NewPutComponentsIDParamsWithContext creates a new PutComponentsIDParams object
// with the ability to set a context for a request.
func NewPutComponentsIDParamsWithContext(ctx context.Context) *PutComponentsIDParams {
	return &PutComponentsIDParams{
		Context: ctx,
	}
}

// NewPutComponentsIDParamsWithHTTPClient creates a new PutComponentsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutComponentsIDParamsWithHTTPClient(client *http.Client) *PutComponentsIDParams {
	return &PutComponentsIDParams{
		HTTPClient: client,
	}
}

/*
PutComponentsIDParams contains all the parameters to send to the API endpoint

	for the put components ID operation.

	Typically these are written to a http.Request.
*/
type PutComponentsIDParams struct {

	/* ID.

	   ID компонента
	*/
	ID string

	/* Request.

	   Данные для обновления
	*/
	Request *models.HTTPUpdateComponent

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put components ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutComponentsIDParams) WithDefaults() *PutComponentsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put components ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutComponentsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put components ID params
func (o *PutComponentsIDParams) WithTimeout(timeout time.Duration) *PutComponentsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put components ID params
func (o *PutComponentsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put components ID params
func (o *PutComponentsIDParams) WithContext(ctx context.Context) *PutComponentsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put components ID params
func (o *PutComponentsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put components ID params
func (o *PutComponentsIDParams) WithHTTPClient(client *http.Client) *PutComponentsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put components ID params
func (o *PutComponentsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the put components ID params
func (o *PutComponentsIDParams) WithID(id string) *PutComponentsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put components ID params
func (o *PutComponentsIDParams) SetID(id string) {
	o.ID = id
}

// WithRequest adds the request to the put components ID params
func (o *PutComponentsIDParams) WithRequest(request *models.HTTPUpdateComponent) *PutComponentsIDParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the put components ID params
func (o *PutComponentsIDParams) SetRequest(request *models.HTTPUpdateComponent) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PutComponentsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
