// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InternalAdapterHandlerHTTPUser internal adapter handler http user
//
// swagger:model internal_adapter_handler_http.User
type InternalAdapterHandlerHTTPUser struct {

	// name
	// Example: Иван Иванов
	Name string `json:"name,omitempty"`

	// user id
	// Example: 123e4567-e89b-12d3-a456-426614174000
	UserID string `json:"user_id,omitempty"`
}

// Validate validates this internal adapter handler http user
func (m *InternalAdapterHandlerHTTPUser) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this internal adapter handler http user based on context it is used
func (m *InternalAdapterHandlerHTTPUser) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InternalAdapterHandlerHTTPUser) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InternalAdapterHandlerHTTPUser) UnmarshalBinary(b []byte) error {
	var res InternalAdapterHandlerHTTPUser
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
