// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InternalAdapterHandlerHTTPSuccessResponse internal adapter handler http success response
//
// swagger:model internal_adapter_handler_http.successResponse
type InternalAdapterHandlerHTTPSuccessResponse struct {

	// data
	Data any `json:"data,omitempty"`

	// message
	// Example: Success message
	Message string `json:"message,omitempty"`

	// success
	// Example: true
	Success bool `json:"success,omitempty"`
}

// Validate validates this internal adapter handler http success response
func (m *InternalAdapterHandlerHTTPSuccessResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this internal adapter handler http success response based on context it is used
func (m *InternalAdapterHandlerHTTPSuccessResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InternalAdapterHandlerHTTPSuccessResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InternalAdapterHandlerHTTPSuccessResponse) UnmarshalBinary(b []byte) error {
	var res InternalAdapterHandlerHTTPSuccessResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
