// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InternalAdapterHandlerHTTPUpdateBike internal adapter handler http update bike
//
// swagger:model internal_adapter_handler_http.UpdateBike
type InternalAdapterHandlerHTTPUpdateBike struct {

	// mileage
	// Example: 2000
	Mileage int64 `json:"mileage,omitempty"`

	// model
	// Example: New Model
	Model string `json:"model,omitempty"`

	// type
	// Example: mountain
	Type string `json:"type,omitempty"`
}

// Validate validates this internal adapter handler http update bike
func (m *InternalAdapterHandlerHTTPUpdateBike) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this internal adapter handler http update bike based on context it is used
func (m *InternalAdapterHandlerHTTPUpdateBike) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InternalAdapterHandlerHTTPUpdateBike) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InternalAdapterHandlerHTTPUpdateBike) UnmarshalBinary(b []byte) error {
	var res InternalAdapterHandlerHTTPUpdateBike
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
