// Code generated by go-swagger; DO NOT EDIT.

package components

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new components API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new components API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new components API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for components API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	DeleteComponentsID(params *DeleteComponentsIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteComponentsIDOK, error)

	GetComponentsID(params *GetComponentsIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetComponentsIDOK, error)

	PostComponents(params *PostComponentsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostComponentsCreated, error)

	PutComponentsID(params *PutComponentsIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutComponentsIDOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
DeleteComponentsID удалитьs компонент

Удаление компонента
*/
func (a *Client) DeleteComponentsID(params *DeleteComponentsIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteComponentsIDOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteComponentsIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteComponentsID",
		Method:             "DELETE",
		PathPattern:        "/components/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteComponentsIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteComponentsIDOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteComponentsID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetComponentsID получитьs компонент

Получение информации о компоненте по ID
*/
func (a *Client) GetComponentsID(params *GetComponentsIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetComponentsIDOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetComponentsIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetComponentsID",
		Method:             "GET",
		PathPattern:        "/components/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetComponentsIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetComponentsIDOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetComponentsID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostComponents создатьs компонент

Добавление компонента к байку
*/
func (a *Client) PostComponents(params *PostComponentsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostComponentsCreated, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostComponentsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostComponents",
		Method:             "POST",
		PathPattern:        "/components",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostComponentsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostComponentsCreated)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostComponents: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PutComponentsID обновитьs компонент

Обновление данных компонента
*/
func (a *Client) PutComponentsID(params *PutComponentsIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutComponentsIDOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPutComponentsIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PutComponentsID",
		Method:             "PUT",
		PathPattern:        "/components/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PutComponentsIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PutComponentsIDOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PutComponentsID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
