// Code generated by go-swagger; DO NOT EDIT.

package bikes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetBikesIDWithComponentsParams creates a new GetBikesIDWithComponentsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBikesIDWithComponentsParams() *GetBikesIDWithComponentsParams {
	return &GetBikesIDWithComponentsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBikesIDWithComponentsParamsWithTimeout creates a new GetBikesIDWithComponentsParams object
// with the ability to set a timeout on a request.
func NewGetBikesIDWithComponentsParamsWithTimeout(timeout time.Duration) *GetBikesIDWithComponentsParams {
	return &GetBikesIDWithComponentsParams{
		timeout: timeout,
	}
}

// NewGetBikesIDWithComponentsParamsWithContext creates a new GetBikesIDWithComponentsParams object
// with the ability to set a context for a request.
func NewGetBikesIDWithComponentsParamsWithContext(ctx context.Context) *GetBikesIDWithComponentsParams {
	return &GetBikesIDWithComponentsParams{
		Context: ctx,
	}
}

// NewGetBikesIDWithComponentsParamsWithHTTPClient creates a new GetBikesIDWithComponentsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBikesIDWithComponentsParamsWithHTTPClient(client *http.Client) *GetBikesIDWithComponentsParams {
	return &GetBikesIDWithComponentsParams{
		HTTPClient: client,
	}
}

/*
GetBikesIDWithComponentsParams contains all the parameters to send to the API endpoint

	for the get bikes ID with components operation.

	Typically these are written to a http.Request.
*/
type GetBikesIDWithComponentsParams struct {

	/* ID.

	   ID байка
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get bikes ID with components params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBikesIDWithComponentsParams) WithDefaults() *GetBikesIDWithComponentsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get bikes ID with components params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBikesIDWithComponentsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get bikes ID with components params
func (o *GetBikesIDWithComponentsParams) WithTimeout(timeout time.Duration) *GetBikesIDWithComponentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get bikes ID with components params
func (o *GetBikesIDWithComponentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get bikes ID with components params
func (o *GetBikesIDWithComponentsParams) WithContext(ctx context.Context) *GetBikesIDWithComponentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get bikes ID with components params
func (o *GetBikesIDWithComponentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get bikes ID with components params
func (o *GetBikesIDWithComponentsParams) WithHTTPClient(client *http.Client) *GetBikesIDWithComponentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get bikes ID with components params
func (o *GetBikesIDWithComponentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get bikes ID with components params
func (o *GetBikesIDWithComponentsParams) WithID(id string) *GetBikesIDWithComponentsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get bikes ID with components params
func (o *GetBikesIDWithComponentsParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetBikesIDWithComponentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
