// Code generated by go-swagger; DO NOT EDIT.

package bikes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetBikesIDWithUserParams creates a new GetBikesIDWithUserParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBikesIDWithUserParams() *GetBikesIDWithUserParams {
	return &GetBikesIDWithUserParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBikesIDWithUserParamsWithTimeout creates a new GetBikesIDWithUserParams object
// with the ability to set a timeout on a request.
func NewGetBikesIDWithUserParamsWithTimeout(timeout time.Duration) *GetBikesIDWithUserParams {
	return &GetBikesIDWithUserParams{
		timeout: timeout,
	}
}

// NewGetBikesIDWithUserParamsWithContext creates a new GetBikesIDWithUserParams object
// with the ability to set a context for a request.
func NewGetBikesIDWithUserParamsWithContext(ctx context.Context) *GetBikesIDWithUserParams {
	return &GetBikesIDWithUserParams{
		Context: ctx,
	}
}

// NewGetBikesIDWithUserParamsWithHTTPClient creates a new GetBikesIDWithUserParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBikesIDWithUserParamsWithHTTPClient(client *http.Client) *GetBikesIDWithUserParams {
	return &GetBikesIDWithUserParams{
		HTTPClient: client,
	}
}

/*
GetBikesIDWithUserParams contains all the parameters to send to the API endpoint

	for the get bikes ID with user operation.

	Typically these are written to a http.Request.
*/
type GetBikesIDWithUserParams struct {

	/* ID.

	   ID байка
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get bikes ID with user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBikesIDWithUserParams) WithDefaults() *GetBikesIDWithUserParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get bikes ID with user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBikesIDWithUserParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get bikes ID with user params
func (o *GetBikesIDWithUserParams) WithTimeout(timeout time.Duration) *GetBikesIDWithUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get bikes ID with user params
func (o *GetBikesIDWithUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get bikes ID with user params
func (o *GetBikesIDWithUserParams) WithContext(ctx context.Context) *GetBikesIDWithUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get bikes ID with user params
func (o *GetBikesIDWithUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get bikes ID with user params
func (o *GetBikesIDWithUserParams) WithHTTPClient(client *http.Client) *GetBikesIDWithUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get bikes ID with user params
func (o *GetBikesIDWithUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get bikes ID with user params
func (o *GetBikesIDWithUserParams) WithID(id string) *GetBikesIDWithUserParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get bikes ID with user params
func (o *GetBikesIDWithUserParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetBikesIDWithUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
