// Code generated by go-swagger; DO NOT EDIT.

package bikes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sm8ta/webike_bike_microservice_nikita/models"
)

// GetBikesIDWithUserReader is a Reader for the GetBikesIDWithUser structure.
type GetBikesIDWithUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBikesIDWithUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetBikesIDWithUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetBikesIDWithUserUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetBikesIDWithUserNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /bikes/{id}/with-user] GetBikesIDWithUser", response, response.Code())
	}
}

// NewGetBikesIDWithUserOK creates a GetBikesIDWithUserOK with default headers values
func NewGetBikesIDWithUserOK() *GetBikesIDWithUserOK {
	return &GetBikesIDWithUserOK{}
}

/*
GetBikesIDWithUserOK describes a response with status code 200, with default header values.

Байк с пользователем
*/
type GetBikesIDWithUserOK struct {
	Payload *models.HTTPSuccessResponse
}

// IsSuccess returns true when this get bikes Id with user o k response has a 2xx status code
func (o *GetBikesIDWithUserOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get bikes Id with user o k response has a 3xx status code
func (o *GetBikesIDWithUserOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get bikes Id with user o k response has a 4xx status code
func (o *GetBikesIDWithUserOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get bikes Id with user o k response has a 5xx status code
func (o *GetBikesIDWithUserOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get bikes Id with user o k response a status code equal to that given
func (o *GetBikesIDWithUserOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get bikes Id with user o k response
func (o *GetBikesIDWithUserOK) Code() int {
	return 200
}

func (o *GetBikesIDWithUserOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /bikes/{id}/with-user][%d] getBikesIdWithUserOK %s", 200, payload)
}

func (o *GetBikesIDWithUserOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /bikes/{id}/with-user][%d] getBikesIdWithUserOK %s", 200, payload)
}

func (o *GetBikesIDWithUserOK) GetPayload() *models.HTTPSuccessResponse {
	return o.Payload
}

func (o *GetBikesIDWithUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPSuccessResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetBikesIDWithUserUnauthorized creates a GetBikesIDWithUserUnauthorized with default headers values
func NewGetBikesIDWithUserUnauthorized() *GetBikesIDWithUserUnauthorized {
	return &GetBikesIDWithUserUnauthorized{}
}

/*
GetBikesIDWithUserUnauthorized describes a response with status code 401, with default header values.

Не авторизован
*/
type GetBikesIDWithUserUnauthorized struct {
	Payload *models.HTTPErrorResponse
}

// IsSuccess returns true when this get bikes Id with user unauthorized response has a 2xx status code
func (o *GetBikesIDWithUserUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get bikes Id with user unauthorized response has a 3xx status code
func (o *GetBikesIDWithUserUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get bikes Id with user unauthorized response has a 4xx status code
func (o *GetBikesIDWithUserUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get bikes Id with user unauthorized response has a 5xx status code
func (o *GetBikesIDWithUserUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get bikes Id with user unauthorized response a status code equal to that given
func (o *GetBikesIDWithUserUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get bikes Id with user unauthorized response
func (o *GetBikesIDWithUserUnauthorized) Code() int {
	return 401
}

func (o *GetBikesIDWithUserUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /bikes/{id}/with-user][%d] getBikesIdWithUserUnauthorized %s", 401, payload)
}

func (o *GetBikesIDWithUserUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /bikes/{id}/with-user][%d] getBikesIdWithUserUnauthorized %s", 401, payload)
}

func (o *GetBikesIDWithUserUnauthorized) GetPayload() *models.HTTPErrorResponse {
	return o.Payload
}

func (o *GetBikesIDWithUserUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetBikesIDWithUserNotFound creates a GetBikesIDWithUserNotFound with default headers values
func NewGetBikesIDWithUserNotFound() *GetBikesIDWithUserNotFound {
	return &GetBikesIDWithUserNotFound{}
}

/*
GetBikesIDWithUserNotFound describes a response with status code 404, with default header values.

Байк не найден
*/
type GetBikesIDWithUserNotFound struct {
	Payload *models.HTTPErrorResponse
}

// IsSuccess returns true when this get bikes Id with user not found response has a 2xx status code
func (o *GetBikesIDWithUserNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get bikes Id with user not found response has a 3xx status code
func (o *GetBikesIDWithUserNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get bikes Id with user not found response has a 4xx status code
func (o *GetBikesIDWithUserNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get bikes Id with user not found response has a 5xx status code
func (o *GetBikesIDWithUserNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get bikes Id with user not found response a status code equal to that given
func (o *GetBikesIDWithUserNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get bikes Id with user not found response
func (o *GetBikesIDWithUserNotFound) Code() int {
	return 404
}

func (o *GetBikesIDWithUserNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /bikes/{id}/with-user][%d] getBikesIdWithUserNotFound %s", 404, payload)
}

func (o *GetBikesIDWithUserNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /bikes/{id}/with-user][%d] getBikesIdWithUserNotFound %s", 404, payload)
}

func (o *GetBikesIDWithUserNotFound) GetPayload() *models.HTTPErrorResponse {
	return o.Payload
}

func (o *GetBikesIDWithUserNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
