// Code generated by go-swagger; DO NOT EDIT.

package bikes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/sm8ta/webike_bike_microservice_nikita/models"
)

// NewPostBikesParams creates a new PostBikesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostBikesParams() *PostBikesParams {
	return &PostBikesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostBikesParamsWithTimeout creates a new PostBikesParams object
// with the ability to set a timeout on a request.
func NewPostBikesParamsWithTimeout(timeout time.Duration) *PostBikesParams {
	return &PostBikesParams{
		timeout: timeout,
	}
}

// NewPostBikesParamsWithContext creates a new PostBikesParams object
// with the ability to set a context for a request.
func NewPostBikesParamsWithContext(ctx context.Context) *PostBikesParams {
	return &PostBikesParams{
		Context: ctx,
	}
}

// NewPostBikesParamsWithHTTPClient creates a new PostBikesParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostBikesParamsWithHTTPClient(client *http.Client) *PostBikesParams {
	return &PostBikesParams{
		HTTPClient: client,
	}
}

/*
PostBikesParams contains all the parameters to send to the API endpoint

	for the post bikes operation.

	Typically these are written to a http.Request.
*/
type PostBikesParams struct {

	/* Request.

	   Данные байка
	*/
	Request *models.HTTPBikeRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post bikes params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostBikesParams) WithDefaults() *PostBikesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post bikes params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostBikesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post bikes params
func (o *PostBikesParams) WithTimeout(timeout time.Duration) *PostBikesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post bikes params
func (o *PostBikesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post bikes params
func (o *PostBikesParams) WithContext(ctx context.Context) *PostBikesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post bikes params
func (o *PostBikesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post bikes params
func (o *PostBikesParams) WithHTTPClient(client *http.Client) *PostBikesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post bikes params
func (o *PostBikesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post bikes params
func (o *PostBikesParams) WithRequest(request *models.HTTPBikeRequest) *PostBikesParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post bikes params
func (o *PostBikesParams) SetRequest(request *models.HTTPBikeRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostBikesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
