// Code generated by go-swagger; DO NOT EDIT.

package bikes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sm8ta/webike_bike_microservice_nikita/models"
)

// PostBikesReader is a Reader for the PostBikes structure.
type PostBikesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostBikesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 201:
		result := NewPostBikesCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostBikesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostBikesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /bikes] PostBikes", response, response.Code())
	}
}

// NewPostBikesCreated creates a PostBikesCreated with default headers values
func NewPostBikesCreated() *PostBikesCreated {
	return &PostBikesCreated{}
}

/*
PostBikesCreated describes a response with status code 201, with default header values.

Байк создан
*/
type PostBikesCreated struct {
	Payload *models.HTTPCreateBikeResponse
}

// IsSuccess returns true when this post bikes created response has a 2xx status code
func (o *PostBikesCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post bikes created response has a 3xx status code
func (o *PostBikesCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post bikes created response has a 4xx status code
func (o *PostBikesCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this post bikes created response has a 5xx status code
func (o *PostBikesCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this post bikes created response a status code equal to that given
func (o *PostBikesCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the post bikes created response
func (o *PostBikesCreated) Code() int {
	return 201
}

func (o *PostBikesCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /bikes][%d] postBikesCreated %s", 201, payload)
}

func (o *PostBikesCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /bikes][%d] postBikesCreated %s", 201, payload)
}

func (o *PostBikesCreated) GetPayload() *models.HTTPCreateBikeResponse {
	return o.Payload
}

func (o *PostBikesCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPCreateBikeResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostBikesBadRequest creates a PostBikesBadRequest with default headers values
func NewPostBikesBadRequest() *PostBikesBadRequest {
	return &PostBikesBadRequest{}
}

/*
PostBikesBadRequest describes a response with status code 400, with default header values.

Неверный запрос
*/
type PostBikesBadRequest struct {
	Payload *models.HTTPErrorResponse
}

// IsSuccess returns true when this post bikes bad request response has a 2xx status code
func (o *PostBikesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post bikes bad request response has a 3xx status code
func (o *PostBikesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post bikes bad request response has a 4xx status code
func (o *PostBikesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post bikes bad request response has a 5xx status code
func (o *PostBikesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post bikes bad request response a status code equal to that given
func (o *PostBikesBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post bikes bad request response
func (o *PostBikesBadRequest) Code() int {
	return 400
}

func (o *PostBikesBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /bikes][%d] postBikesBadRequest %s", 400, payload)
}

func (o *PostBikesBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /bikes][%d] postBikesBadRequest %s", 400, payload)
}

func (o *PostBikesBadRequest) GetPayload() *models.HTTPErrorResponse {
	return o.Payload
}

func (o *PostBikesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostBikesUnauthorized creates a PostBikesUnauthorized with default headers values
func NewPostBikesUnauthorized() *PostBikesUnauthorized {
	return &PostBikesUnauthorized{}
}

/*
PostBikesUnauthorized describes a response with status code 401, with default header values.

Не авторизован
*/
type PostBikesUnauthorized struct {
	Payload *models.HTTPErrorResponse
}

// IsSuccess returns true when this post bikes unauthorized response has a 2xx status code
func (o *PostBikesUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post bikes unauthorized response has a 3xx status code
func (o *PostBikesUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post bikes unauthorized response has a 4xx status code
func (o *PostBikesUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post bikes unauthorized response has a 5xx status code
func (o *PostBikesUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post bikes unauthorized response a status code equal to that given
func (o *PostBikesUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post bikes unauthorized response
func (o *PostBikesUnauthorized) Code() int {
	return 401
}

func (o *PostBikesUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /bikes][%d] postBikesUnauthorized %s", 401, payload)
}

func (o *PostBikesUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /bikes][%d] postBikesUnauthorized %s", 401, payload)
}

func (o *PostBikesUnauthorized) GetPayload() *models.HTTPErrorResponse {
	return o.Payload
}

func (o *PostBikesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
