// Code generated by go-swagger; DO NOT EDIT.

package bikes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"webike_bike_microservice_nikita/models"
)

// NewPutBikesIDParams creates a new PutBikesIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutBikesIDParams() *PutBikesIDParams {
	return &PutBikesIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutBikesIDParamsWithTimeout creates a new PutBikesIDParams object
// with the ability to set a timeout on a request.
func NewPutBikesIDParamsWithTimeout(timeout time.Duration) *PutBikesIDParams {
	return &PutBikesIDParams{
		timeout: timeout,
	}
}

// NewPutBikesIDParamsWithContext creates a new PutBikesIDParams object
// with the ability to set a context for a request.
func NewPutBikesIDParamsWithContext(ctx context.Context) *PutBikesIDParams {
	return &PutBikesIDParams{
		Context: ctx,
	}
}

// NewPutBikesIDParamsWithHTTPClient creates a new PutBikesIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutBikesIDParamsWithHTTPClient(client *http.Client) *PutBikesIDParams {
	return &PutBikesIDParams{
		HTTPClient: client,
	}
}

/*
PutBikesIDParams contains all the parameters to send to the API endpoint

	for the put bikes ID operation.

	Typically these are written to a http.Request.
*/
type PutBikesIDParams struct {

	/* ID.

	   ID байка
	*/
	ID string

	/* Request.

	   Данные для обновления
	*/
	Request *models.InternalAdapterHandlerHTTPUpdateBike

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put bikes ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutBikesIDParams) WithDefaults() *PutBikesIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put bikes ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutBikesIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put bikes ID params
func (o *PutBikesIDParams) WithTimeout(timeout time.Duration) *PutBikesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put bikes ID params
func (o *PutBikesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put bikes ID params
func (o *PutBikesIDParams) WithContext(ctx context.Context) *PutBikesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put bikes ID params
func (o *PutBikesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put bikes ID params
func (o *PutBikesIDParams) WithHTTPClient(client *http.Client) *PutBikesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put bikes ID params
func (o *PutBikesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the put bikes ID params
func (o *PutBikesIDParams) WithID(id string) *PutBikesIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put bikes ID params
func (o *PutBikesIDParams) SetID(id string) {
	o.ID = id
}

// WithRequest adds the request to the put bikes ID params
func (o *PutBikesIDParams) WithRequest(request *models.InternalAdapterHandlerHTTPUpdateBike) *PutBikesIDParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the put bikes ID params
func (o *PutBikesIDParams) SetRequest(request *models.InternalAdapterHandlerHTTPUpdateBike) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PutBikesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
