// Code generated by go-swagger; DO NOT EDIT.

package bikes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteBikesIDParams creates a new DeleteBikesIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteBikesIDParams() *DeleteBikesIDParams {
	return &DeleteBikesIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteBikesIDParamsWithTimeout creates a new DeleteBikesIDParams object
// with the ability to set a timeout on a request.
func NewDeleteBikesIDParamsWithTimeout(timeout time.Duration) *DeleteBikesIDParams {
	return &DeleteBikesIDParams{
		timeout: timeout,
	}
}

// NewDeleteBikesIDParamsWithContext creates a new DeleteBikesIDParams object
// with the ability to set a context for a request.
func NewDeleteBikesIDParamsWithContext(ctx context.Context) *DeleteBikesIDParams {
	return &DeleteBikesIDParams{
		Context: ctx,
	}
}

// NewDeleteBikesIDParamsWithHTTPClient creates a new DeleteBikesIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteBikesIDParamsWithHTTPClient(client *http.Client) *DeleteBikesIDParams {
	return &DeleteBikesIDParams{
		HTTPClient: client,
	}
}

/*
DeleteBikesIDParams contains all the parameters to send to the API endpoint

	for the delete bikes ID operation.

	Typically these are written to a http.Request.
*/
type DeleteBikesIDParams struct {

	/* ID.

	   ID байка
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete bikes ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteBikesIDParams) WithDefaults() *DeleteBikesIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete bikes ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteBikesIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete bikes ID params
func (o *DeleteBikesIDParams) WithTimeout(timeout time.Duration) *DeleteBikesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete bikes ID params
func (o *DeleteBikesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete bikes ID params
func (o *DeleteBikesIDParams) WithContext(ctx context.Context) *DeleteBikesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete bikes ID params
func (o *DeleteBikesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete bikes ID params
func (o *DeleteBikesIDParams) WithHTTPClient(client *http.Client) *DeleteBikesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete bikes ID params
func (o *DeleteBikesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete bikes ID params
func (o *DeleteBikesIDParams) WithID(id string) *DeleteBikesIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete bikes ID params
func (o *DeleteBikesIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteBikesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
