// Code generated by go-swagger; DO NOT EDIT.

package bikes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetBikesIDParams creates a new GetBikesIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBikesIDParams() *GetBikesIDParams {
	return &GetBikesIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBikesIDParamsWithTimeout creates a new GetBikesIDParams object
// with the ability to set a timeout on a request.
func NewGetBikesIDParamsWithTimeout(timeout time.Duration) *GetBikesIDParams {
	return &GetBikesIDParams{
		timeout: timeout,
	}
}

// NewGetBikesIDParamsWithContext creates a new GetBikesIDParams object
// with the ability to set a context for a request.
func NewGetBikesIDParamsWithContext(ctx context.Context) *GetBikesIDParams {
	return &GetBikesIDParams{
		Context: ctx,
	}
}

// NewGetBikesIDParamsWithHTTPClient creates a new GetBikesIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBikesIDParamsWithHTTPClient(client *http.Client) *GetBikesIDParams {
	return &GetBikesIDParams{
		HTTPClient: client,
	}
}

/*
GetBikesIDParams contains all the parameters to send to the API endpoint

	for the get bikes ID operation.

	Typically these are written to a http.Request.
*/
type GetBikesIDParams struct {

	/* ID.

	   ID байка
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get bikes ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBikesIDParams) WithDefaults() *GetBikesIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get bikes ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBikesIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get bikes ID params
func (o *GetBikesIDParams) WithTimeout(timeout time.Duration) *GetBikesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get bikes ID params
func (o *GetBikesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get bikes ID params
func (o *GetBikesIDParams) WithContext(ctx context.Context) *GetBikesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get bikes ID params
func (o *GetBikesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get bikes ID params
func (o *GetBikesIDParams) WithHTTPClient(client *http.Client) *GetBikesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get bikes ID params
func (o *GetBikesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get bikes ID params
func (o *GetBikesIDParams) WithID(id string) *GetBikesIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get bikes ID params
func (o *GetBikesIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetBikesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
