// Code generated by go-swagger; DO NOT EDIT.

package bikes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetBikesMyParams creates a new GetBikesMyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBikesMyParams() *GetBikesMyParams {
	return &GetBikesMyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBikesMyParamsWithTimeout creates a new GetBikesMyParams object
// with the ability to set a timeout on a request.
func NewGetBikesMyParamsWithTimeout(timeout time.Duration) *GetBikesMyParams {
	return &GetBikesMyParams{
		timeout: timeout,
	}
}

// NewGetBikesMyParamsWithContext creates a new GetBikesMyParams object
// with the ability to set a context for a request.
func NewGetBikesMyParamsWithContext(ctx context.Context) *GetBikesMyParams {
	return &GetBikesMyParams{
		Context: ctx,
	}
}

// NewGetBikesMyParamsWithHTTPClient creates a new GetBikesMyParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBikesMyParamsWithHTTPClient(client *http.Client) *GetBikesMyParams {
	return &GetBikesMyParams{
		HTTPClient: client,
	}
}

/*
GetBikesMyParams contains all the parameters to send to the API endpoint

	for the get bikes my operation.

	Typically these are written to a http.Request.
*/
type GetBikesMyParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get bikes my params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBikesMyParams) WithDefaults() *GetBikesMyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get bikes my params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBikesMyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get bikes my params
func (o *GetBikesMyParams) WithTimeout(timeout time.Duration) *GetBikesMyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get bikes my params
func (o *GetBikesMyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get bikes my params
func (o *GetBikesMyParams) WithContext(ctx context.Context) *GetBikesMyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get bikes my params
func (o *GetBikesMyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get bikes my params
func (o *GetBikesMyParams) WithHTTPClient(client *http.Client) *GetBikesMyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get bikes my params
func (o *GetBikesMyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetBikesMyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
