// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HTTPBikeInfo http bike info
//
// swagger:model http.BikeInfo
type HTTPBikeInfo struct {

	// bike id
	BikeID string `json:"bike_id,omitempty"`

	// bike name
	BikeName string `json:"bike_name,omitempty"`

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// mileage
	Mileage int64 `json:"mileage,omitempty"`

	// model
	Model string `json:"model,omitempty"`

	// type
	Type string `json:"type,omitempty"`

	// updated at
	UpdatedAt string `json:"updated_at,omitempty"`

	// user id
	UserID string `json:"user_id,omitempty"`

	// year
	Year int64 `json:"year,omitempty"`
}

// Validate validates this http bike info
func (m *HTTPBikeInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this http bike info based on context it is used
func (m *HTTPBikeInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HTTPBikeInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HTTPBikeInfo) UnmarshalBinary(b []byte) error {
	var res HTTPBikeInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
