// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HTTPDeleteBikeResponse http delete bike response
//
// swagger:model http.DeleteBikeResponse
type HTTPDeleteBikeResponse struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this http delete bike response
func (m *HTTPDeleteBikeResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this http delete bike response based on context it is used
func (m *HTTPDeleteBikeResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HTTPDeleteBikeResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HTTPDeleteBikeResponse) UnmarshalBinary(b []byte) error {
	var res HTTPDeleteBikeResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
