// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HTTPGetMyBikesResponse http get my bikes response
//
// swagger:model http.GetMyBikesResponse
type HTTPGetMyBikesResponse struct {

	// bikes
	Bikes []*HTTPBikeInfo `json:"bikes"`

	// count
	Count int64 `json:"count,omitempty"`
}

// Validate validates this http get my bikes response
func (m *HTTPGetMyBikesResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBikes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HTTPGetMyBikesResponse) validateBikes(formats strfmt.Registry) error {
	if swag.IsZero(m.Bikes) { // not required
		return nil
	}

	for i := 0; i < len(m.Bikes); i++ {
		if swag.IsZero(m.Bikes[i]) { // not required
			continue
		}

		if m.Bikes[i] != nil {
			if err := m.Bikes[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("bikes" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("bikes" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this http get my bikes response based on the context it is used
func (m *HTTPGetMyBikesResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBikes(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HTTPGetMyBikesResponse) contextValidateBikes(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Bikes); i++ {

		if m.Bikes[i] != nil {

			if swag.IsZero(m.Bikes[i]) { // not required
				return nil
			}

			if err := m.Bikes[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("bikes" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("bikes" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *HTTPGetMyBikesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HTTPGetMyBikesResponse) UnmarshalBinary(b []byte) error {
	var res HTTPGetMyBikesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
