// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InternalAdapterHandlerHTTPUpdateComponent internal adapter handler http update component
//
// swagger:model internal_adapter_handler_http.UpdateComponent
type InternalAdapterHandlerHTTPUpdateComponent struct {

	// brand
	// Example: Shimano
	Brand string `json:"brand,omitempty"`

	// installed mileage
	// Example: 1000
	InstalledMileage int64 `json:"installed_mileage,omitempty"`

	// max mileage
	// Example: 5000
	MaxMileage int64 `json:"max_mileage,omitempty"`

	// model
	// Example: XT
	Model string `json:"model,omitempty"`

	// name
	// Example: handlebars
	Name string `json:"name,omitempty"`
}

// Validate validates this internal adapter handler http update component
func (m *InternalAdapterHandlerHTTPUpdateComponent) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this internal adapter handler http update component based on context it is used
func (m *InternalAdapterHandlerHTTPUpdateComponent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InternalAdapterHandlerHTTPUpdateComponent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InternalAdapterHandlerHTTPUpdateComponent) UnmarshalBinary(b []byte) error {
	var res InternalAdapterHandlerHTTPUpdateComponent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
