// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InternalAdapterHandlerHTTPErrorResponse internal adapter handler http error response
//
// swagger:model internal_adapter_handler_http.errorResponse
type InternalAdapterHandlerHTTPErrorResponse struct {

	// message
	// Example: Error
	Message string `json:"message,omitempty"`

	// success
	// Example: false
	Success bool `json:"success,omitempty"`
}

// Validate validates this internal adapter handler http error response
func (m *InternalAdapterHandlerHTTPErrorResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this internal adapter handler http error response based on context it is used
func (m *InternalAdapterHandlerHTTPErrorResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InternalAdapterHandlerHTTPErrorResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InternalAdapterHandlerHTTPErrorResponse) UnmarshalBinary(b []byte) error {
	var res InternalAdapterHandlerHTTPErrorResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
